{{ $community := (and .Values.config.snmpCommunity (not .Values.config.snmpCommunitySecret)) }}
{{ $authenticationUsername := (and .Values.config.snmpAuthenticationUsername (not .Values.config.snmpAuthenticationUsernameSecret)) }}
{{ $authenticationPassword := (and .Values.config.snmpAuthenticationPassword (not .Values.config.snmpAuthenticationPasswordSecret)) }}
{{ $privatePassword := (and .Values.config.snmpPrivatePassword (not .Values.config.snmpPrivatePasswordSecret)) }}
{{- if (or $community $authenticationUsername $authenticationPassword $privatePassword) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "alertmanager-snmp-notifier.fullname" . }}
  labels:
    app: {{ template "alertmanager-snmp-notifier.name" . }}
    chart: {{ template "alertmanager-snmp-notifier.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  {{- if $community }}
  community: {{ .Values.config.snmpCommunity | b64enc }}
  {{- end -}}
  {{- if $authenticationUsername }}
  authenticationUsername: {{ .Values.config.snmpAuthenticationUsername | b64enc }}
  {{- end -}}
  {{- if $authenticationPassword }}
  authenticationPassword: {{ .Values.config.snmpAuthenticationPassword | b64enc }}
  {{- end -}}
  {{- if $privatePassword }}
  privatePassword: {{ .Values.config.snmpPrivatePassword | b64enc }}
  {{- end -}}
{{- end -}}
